#! /bin/sh

sxhkd &

. "${HOME}/.cache/wal/colors.sh"

i=1
for monitor in $(bspc query -M); do
bspc monitor "$monitor" \
        -n "$i" \
        -d {α,β,γ,δ,ε,ζ}
    let i++
done

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color9"
bspc config focused_border_color "$color9"
#bspc config focused_border_color "#afa087"
bspc config active_border_color "$color9"

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a \* floating=on
bspc rule -a \* state=floating
